version: "3"
services: 
    mysql:
        image: mysql:5.5
        ports:
            - "3306:3306"
        expose:
            - 3306
        volumes:
            - .dockerfiles/mysql/data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: myapp
    app:
        build: 
            context: ./
            dockerfile: .dockerfiles/php.dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./api:/var/www/html
        links:
            - mysql
    nginx:
        image: nginx:stable
        ports:
            - 8080:80
        volumes:
            - ./api/app:var/www/html
        links:
            - app
